# Generated by Django 4.2.5 on 2024-02-14 18:37

from django.db import migrations, models
import services.uploader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject1', models.TextField(verbose_name='subject')),
                ('image1', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_about)),
                ('subject2', models.TextField(verbose_name='subject')),
                ('image2', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_about)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='ad')),
                ('surname', models.CharField(max_length=255, verbose_name='soyad')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('phone', models.CharField(max_length=255, verbose_name='telefon')),
                ('adress1', models.CharField(max_length=255, verbose_name='adress 1')),
                ('adress2', models.CharField(max_length=255, verbose_name='adress 2')),
                ('country', models.CharField(choices=[('usa', 'Amerika'), ('az', 'Azerbaijan'), ('eu', 'Europa'), ('as', 'Asia')], max_length=255, verbose_name='olke adlari')),
                ('city', models.CharField(max_length=255, verbose_name='sheher adi')),
                ('state', models.CharField(max_length=255, verbose_name='dovlet')),
                ('zipcode', models.CharField(max_length=255, verbose_name='olke kodu')),
            ],
            options={
                'verbose_name': 'checkout',
                'verbose_name_plural': 'checkout',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='ad ve soyad')),
                ('email', models.CharField(max_length=255, verbose_name='email adress')),
                ('subject', models.CharField(max_length=255, verbose_name='movzu')),
                ('mesage', models.TextField(verbose_name='mesaj')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contactlar',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MainDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('adresss', models.CharField(max_length=255, verbose_name='adress')),
                ('phones', models.CharField(max_length=255, verbose_name='phones')),
                ('locations', models.TextField(blank=True, null=True, verbose_name='locations')),
            ],
            options={
                'verbose_name': 'elaqe melumati',
                'verbose_name_plural': 'elaqe melumatlari',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.TextField(verbose_name='mehsulun olcusu')),
                ('text', models.TextField(verbose_name='metn')),
            ],
            options={
                'verbose_name': 'olcu',
                'verbose_name_plural': 'olculer',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Partniors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_partniors)),
            ],
            options={
                'verbose_name': 'partnior sekil',
                'verbose_name_plural': 'partnior sekiller',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('name', models.CharField(max_length=255, verbose_name='mehsulun adi')),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_projects)),
            ],
            options={
                'verbose_name': 'mehsul',
                'verbose_name_plural': 'mehsullar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SosialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sosial_name', models.CharField(choices=[('insta', 'Instagram'), ('fb', 'Facebook'), ('wp', 'WhatsApp'), ('twitter', 'Twitter'), ('linkedin', 'Linkedin'), ('tiktok', 'Tiktok')], max_length=255, verbose_name='sosial media hesabi')),
                ('sosial_link', models.TextField(verbose_name='sosial media linki')),
            ],
            options={
                'verbose_name': 'sosial media hesabi',
                'verbose_name_plural': 'sosial media hesablari',
                'ordering': ('sosial_name',),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.TextField(verbose_name='iscinin adi')),
                ('profession', models.CharField(max_length=255, verbose_name='peshesi')),
                ('image', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_team)),
                ('imagehover', models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_team)),
            ],
            options={
                'verbose_name': 'reng',
                'verbose_name_plural': 'rengler',
                'ordering': ('-created_at',),
            },
        ),
    ]
