# Generated by Django 4.2.5 on 2024-02-15 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_blogcategory_about_slogan_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
