# Generated by Django 4.2.5 on 2024-02-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_delete_checkout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-created_at',), 'verbose_name': 'blog', 'verbose_name_plural': 'bloglar'},
        ),
        migrations.AlterModelOptions(
            name='ourservices',
            options={'ordering': ('-created_at',), 'verbose_name': 'bizim xidmet', 'verbose_name_plural': 'bizim xidmetler'},
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'ordering': ('-created_at',), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-created_at',), 'verbose_name': 'team', 'verbose_name_plural': 'teams'},
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='name',
            field=models.TextField(verbose_name='adi'),
        ),
    ]
