# Generated by Django 4.2.5 on 2024-02-15 18:13

from django.db import migrations, models
import django.db.models.deletion
import services.uploader


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_blog_options_alter_ourservices_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='projects',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_projects),
        ),
        migrations.AddField(
            model_name='projects',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_projects),
        ),
        migrations.AddField(
            model_name='projects',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to=services.uploader.Uploader.upload_photo_projects),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.blogcategory'),
        ),
        migrations.AddField(
            model_name='projects',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='metn'),
        ),
    ]
