# Generated by Django 5.0.2 on 2024-02-23 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_rename_image_projects_image1_projects_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='subject1_az',
            field=models.TextField(null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='about',
            name='subject1_en',
            field=models.TextField(null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='about',
            name='subject1_ru',
            field=models.TextField(null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='about',
            name='subject2_az',
            field=models.TextField(null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='about',
            name='subject2_en',
            field=models.TextField(null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='about',
            name='subject2_ru',
            field=models.TextField(null=True, verbose_name='subject'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category_az',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.blogcategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.blogcategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.blogcategory'),
        ),
        migrations.AddField(
            model_name='blog',
            name='information_az',
            field=models.TextField(null=True, verbose_name='melumat'),
        ),
        migrations.AddField(
            model_name='blog',
            name='information_en',
            field=models.TextField(null=True, verbose_name='melumat'),
        ),
        migrations.AddField(
            model_name='blog',
            name='information_ru',
            field=models.TextField(null=True, verbose_name='melumat'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_az',
            field=models.CharField(max_length=255, null=True, verbose_name='blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='blog'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='blog'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='name_az',
            field=models.TextField(null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='name_en',
            field=models.TextField(null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='adi'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='text_az',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='text_en',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='ourservices',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_az',
            field=models.CharField(max_length=255, null=True, verbose_name='mehsulun adi'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='mehsulun adi'),
        ),
        migrations.AddField(
            model_name='projects',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='mehsulun adi'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category_az',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.blogcategory'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category_en',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.blogcategory'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_category_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.blogcategory'),
        ),
        migrations.AddField(
            model_name='projects',
            name='text_az',
            field=models.TextField(blank=True, null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='projects',
            name='text_en',
            field=models.TextField(blank=True, null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='projects',
            name='text_ru',
            field=models.TextField(blank=True, null=True, verbose_name='metn'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_az',
            field=models.TextField(null=True, verbose_name='iscinin adi'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_en',
            field=models.TextField(null=True, verbose_name='iscinin adi'),
        ),
        migrations.AddField(
            model_name='team',
            name='name_ru',
            field=models.TextField(null=True, verbose_name='iscinin adi'),
        ),
        migrations.AddField(
            model_name='team',
            name='profession_az',
            field=models.CharField(max_length=255, null=True, verbose_name='peshesi'),
        ),
        migrations.AddField(
            model_name='team',
            name='profession_en',
            field=models.CharField(max_length=255, null=True, verbose_name='peshesi'),
        ),
        migrations.AddField(
            model_name='team',
            name='profession_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='peshesi'),
        ),
    ]
